experement_name: Base inception_v4

# base_weights_path: ...

model_info:
  model_type: inceptionv4 # possible [resnet50, resnet101, resnet152, xception, inceptionv4, seresnext]
  num_classes: 2
  pretrained: True

loader_data:
  dataset: Facebook
  train_path: /fast_data/rew_data
  valid_path: /fast_data/rew_data
  test_path: /fast_data/rew_data
  df_train_path: /fast_data/train_data.csv
  df_valid_path: /fast_data/valid_data.csv
  df_test_path: /fast_data/test_data.csv
  side_size: 299
  batch_size: 40
  num_workers: 0

loss: Focal # possible [Focal, CrossEntropy]
gpus: '0, 1'
benchmark: True
use_fp16: False
train_percent_check: 1.0
val_percent_check: 1.0
early_stop_params:
  patience: 20

cp_saver_params:
  savedir: /fast_data/checkpoints
  metric: val_loss
  mode: min
  prefix: val_loss
base_logdir: /fast_data/checkpoints

gradient_clip_val: 0.0
epochs: 1000
opt_name: Adam
opt_params:
  lr: 0.01
# sched_name: ReduceLROnPlateau
# sched_params:
#   patience: 3
#   factor: 0.1


infer_chekpoint: ...